// assets/js/app/Form/CheckboxComponent.jsx
import React from 'react'
import { hot } from 'react-hot-loader/root'
import PropTypes from 'prop-types'
import {
  getHelpId,
  getInputClassName,
  getLabelClassName,
  getRules,
  isRequired,
  getValueFromEvent,
  useValueAndError, getError
} from './Form'

function CheckboxComponent ({ rulesInString, initialValue, initialError, attr, id, name, help, label }) {
  const rules = getRules(rulesInString)
  let required = isRequired(rules)
  const { value, error, setError, setValue } = useValueAndError(initialValue, initialError)

  return (
    <div className="form-group">
      <div className="custom-control custom-switch">

        <input type="checkbox" className={getInputClassName(error, 'custom-control-input')} id={id} name={name}
               required={required} aria-describedby={getHelpId(help, id)} checked={value}
               onChange={event => setValue(getValueFromEvent(event))}
               onBlur={() => setError(getError(rules, value))} {...attr}
        />

        {
          label !== '' &&
          <label htmlFor={id} className={getLabelClassName(error, 'custom-control-label')}>{label}</label>
        }

        {
          error !== '' &&
          <div className='invalid-feedback'>{error}</div>
        }


        {
          help &&
          <small id={getHelpId(help, id)} className='form-text text-muted w-100'>{help}</small>
        }
        {
          value === false && <input type='hidden' name={name} value='0'/>
        }
      </div>
    </div>
  )
}

CheckboxComponent.propTypes = {
  id        : PropTypes.string.isRequired,
  parentForm: PropTypes.instanceOf(HTMLFormElement),
  attr      : PropTypes.object,
  label     : PropTypes.string,
  rules     : PropTypes.string
}

export default hot(CheckboxComponent)

// assets/js/src/Bootstrap/components/CheckboxComponent.vue
<template>
    <div class="form-group">
        <div class="custom-control custom-checkbox">
            <input :name="getName" type="hidden" v-if="!getValue" value=""/>

            <input :checked="getValue" :class="getInputClass" :id="getId" :name="getName" class="custom-control-input"
                   type="checkbox"
                   @change="change($event.target.checked)" value="1">

            <label class="custom-control-label" :for="getId" style="cursor: pointer">{{ label }}</label>

            <required-component :label="label" :required="isRequired"></required-component>

            <error-component :error="getError"></error-component>
        </div>
    </div>
</template>

<script>
    import RequiredComponent from "../includes/RequiredComponent";
    import ErrorComponent from "../includes/ErrorComponent";
    import FormElementMixin from "../includes/FormElementMixin";

    export default {
        components: {ErrorComponent, RequiredComponent},
        mixins: [FormElementMixin],
        computed: {
            getInputClass: function () {
                return {
                    'is-invalid': this.getError
                };
            },
        },
    }
</script>
